appGroup=org.example
appVersion=1.0-SNAPSHOT

# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.daemon=false
# org.gradle.priority=normal (low,normal)
# org.gradle.parallel=true (true, false)
# org.gradle.projectcachedir=(.gradle)

# https://mvnrepository.com/artifact/org.jetbrains.dokka/dokka-core
dokkaVersion=2.2.0

# https://mvnrepository.com/artifact/org.jetbrains.dokka/dokka-gradle-plugin
dokkaPluginVersion=2.2.0

# https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-compiler
kotlinVersion=2.4.0

# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core
kotlinxVersion=1.11.0

# https://github.com/pinterest/ktlint/releases
ktLintJar=C:/opt/ktlint/bin/ktlint.jar

# https://mvnrepository.com/artifact/junit/junit
junitVersion=4.13.2

mainClassName=chapter1_2.MainKt
